name: Deploy

on:
  push:
  schedule:
    - cron: '10 10 * * 1'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v1
      with:
        node-version: "16.9"

    - run: |
        rm -rf docs
        npm install
        npm run build
        npx next export
        touch out/.nojekyll
      env:
        GITHUB_TOKEN: ${{ secrets.SUMMARY_TOKEN }}
        PREFIX: /summary

    - uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: out
